#!/bin/bash
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
#
#   Script Name : secrets.conf
#        Author : Ecometer s.n.c.
#          Date : 2025-12-30
#
#   Configuration file
#
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------

# CUSTOM VARIABLE, HASH, ARRAY, CONF

SFTP_URL=""

export PGUSER=''
export PGPASSWORD=''
export PGHOST=''
export PGPORT='6432'
export PGDATABASE='opas_ld'
export TABLE_NAME="clients.data_file_status"

