#
# https://github.com/kraih/mojo/wiki/logrotate
#
# @daily /usr/sbin/logrotate -s /var/www/bobo/logrotate/logrotate.status /var/www/bobo/logrotate/logrotate.conf
#
/var/www/bobo/log/production.log {
    weekly
    copytruncate
    rotate 52
    missingok
    notifempty
}

# rotate 12: keep twelve old log files.
# monthly: rotate once a month.
# compress: compress the rotated files. this uses gzip by default and results in files ending in .gz.
#    The compression command can be changed using the compresscmd option.
# missingok: don’t write an error message if the log file is missing.
# notifempty: don’t rotate the log file if it is empty.

# testing
# /usr/sbin/logrotate -s /var/www/bobo/logrotate/logrotate.status /var/www/bobo/logrotate/logrotate.conf --debug
# /usr/sbin/logrotate -s /var/www/bobo/logrotate/logrotate.status /var/www/bobo/logrotate/logrotate.conf --force
