-- +----------------------------------------------------------------------------------------------+
-- | - Script Name   : foreign_keys.sql                                                           |
-- | - Author        : Ecometer s.n.c.                                                            |
-- | - Creation Date : 2025-03-31                                                                 |
-- | - Update Date   : 2025-06-30                                                                 |
-- | - Description   : Script to create PostgreSQL 'opas' database foreign keys.                  |
-- +----------------------------------------------------------------------------------------------+


ALTER TABLE ONLY audit.rep_qacalibrations ADD CONSTRAINT audit_rep_qacalibrations_fkey FOREIGN KEY (log_user) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY audit.rep_qamaintenances ADD CONSTRAINT audit_rep_qamaintenances_fkey FOREIGN KEY (log_user) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.portal_properties ADD CONSTRAINT bobo_admin_groups_fk1 FOREIGN KEY (portal_id) REFERENCES bobo.portals(portal_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.portal_properties ADD CONSTRAINT bobo_admin_groups_fk2 FOREIGN KEY (admin_gr_id) REFERENCES bobo.groups(gr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.portal_properties ADD CONSTRAINT bobo_admin_groups_fk3 FOREIGN KEY (admin_comp_id) REFERENCES bobo.companies(comp_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.portal_properties ADD CONSTRAINT bobo_admin_groups_fk4 FOREIGN KEY (region_id) REFERENCES main.regions(region_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.faq_arguments ADD CONSTRAINT bobo_faq_arguments_fk1 FOREIGN KEY (faq_page_id) REFERENCES bobo.faq_pages(faq_page_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.group_channels ADD CONSTRAINT bobo_group_channels_fk1 FOREIGN KEY (gr_id) REFERENCES bobo.groups(gr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.group_final_codes ADD CONSTRAINT bobo_group_final_codes_fk1 FOREIGN KEY (gr_id) REFERENCES bobo.groups(gr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.group_final_codes ADD CONSTRAINT bobo_group_final_codes_fk2 FOREIGN KEY (fvc_code_id) REFERENCES metadata.final_validation_codes(fvc_code_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.group_networks ADD CONSTRAINT bobo_group_networks_fk1 FOREIGN KEY (gr_id) REFERENCES bobo.groups(gr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.group_networks ADD CONSTRAINT bobo_group_networks_fk2 FOREIGN KEY (st_network_id) REFERENCES metadata.stations_network_type(st_network_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.group_pages ADD CONSTRAINT bobo_group_pages_fk1 FOREIGN KEY (gr_id) REFERENCES bobo.groups(gr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.group_pages ADD CONSTRAINT bobo_group_pages_fk2 FOREIGN KEY (page_id) REFERENCES bobo.pages(page_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.group_stations ADD CONSTRAINT bobo_group_stations_fk1 FOREIGN KEY (gr_id) REFERENCES bobo.groups(gr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.group_stations ADD CONSTRAINT bobo_group_stations_fk2 FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.group_channels ADD CONSTRAINT bobo_group_widgets_fk2 FOREIGN KEY (tc_id) REFERENCES gateways.telegram_channels(tc_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.menu_css ADD CONSTRAINT bobo_menu_css_fk1 FOREIGN KEY (mp_id) REFERENCES bobo.menu_pages(mp_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.menu_pages ADD CONSTRAINT bobo_menu_pages_fk1 FOREIGN KEY (menu_id) REFERENCES bobo.menus(menu_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.menu_pages ADD CONSTRAINT bobo_menu_pages_fk2 FOREIGN KEY (page_id) REFERENCES bobo.pages(page_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.group_widgets ADD CONSTRAINT bobo_tools_group_widgets_fk1 FOREIGN KEY (gr_id) REFERENCES bobo.groups(gr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.group_widgets ADD CONSTRAINT bobo_tools_group_widgets_fk2 FOREIGN KEY (wdg_id) REFERENCES bobo_tools.homepage_widgets(wdg_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.user_options ADD CONSTRAINT bobo_tools_user_options_fk1 FOREIGN KEY (option_user) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.user_groups ADD CONSTRAINT bobo_user_groups_fk1 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.user_groups ADD CONSTRAINT bobo_user_groups_fk2 FOREIGN KEY (gr_id) REFERENCES bobo.groups(gr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.users_metadata ADD CONSTRAINT bobo_users_metadata_fk1 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.users_metadata ADD CONSTRAINT bobo_users_metadata_fk2 FOREIGN KEY (comp_id) REFERENCES bobo.companies(comp_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo.users_metadata ADD CONSTRAINT bobo_users_metadata_fk3 FOREIGN KEY (portal_id) REFERENCES bobo.portals(portal_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.analyser_categories ADD CONSTRAINT bobo_tools_analyser_categories_fk1 FOREIGN KEY (cat_owner) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.analyser_category_groups ADD CONSTRAINT bobo_tools_analyser_category_groups_fk1 FOREIGN KEY (cat_id) REFERENCES bobo_tools.analyser_categories(cat_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.analyser_category_groups ADD CONSTRAINT bobo_tools_analyser_category_groups_fk2 FOREIGN KEY (gr_id) REFERENCES bobo.groups(gr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.analyser_trees_groups ADD CONSTRAINT bobo_tools_analyser_category_groups_fk2 FOREIGN KEY (gr_id) REFERENCES bobo.groups(gr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.analyser_macros ADD CONSTRAINT bobo_tools_analyser_macros_fk1 FOREIGN KEY (macro_category) REFERENCES bobo_tools.analyser_categories(cat_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.analyser_options ADD CONSTRAINT bobo_tools_analyser_options_fk1 FOREIGN KEY (option_user) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.analyser_trees ADD CONSTRAINT bobo_tools_analyser_trees_fk1 FOREIGN KEY (tree_owner) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.analyser_trees_groups ADD CONSTRAINT bobo_tools_analyser_trees_groups_fk1 FOREIGN KEY (tree_id) REFERENCES bobo_tools.analyser_trees(tree_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.annotations ADD CONSTRAINT bobo_tools_annotations_fk1 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.dataview_indicators_range ADD CONSTRAINT bobo_tools_dataview_indicators_range_fk1 FOREIGN KEY (param_id) REFERENCES metadata.parameters(param_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.portal_options ADD CONSTRAINT bobo_tools_general_options_fk2 FOREIGN KEY (page_id) REFERENCES bobo.pages(page_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.homepage_links ADD CONSTRAINT bobo_tools_homepage_links_fk1 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.homepage_links ADD CONSTRAINT bobo_tools_homepage_links_fk2 FOREIGN KEY (portal_id) REFERENCES bobo.portals(portal_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.parameters_options ADD CONSTRAINT bobo_tools_parameters_options_fk1 FOREIGN KEY (param_id) REFERENCES metadata.parameters(param_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.portal_options ADD CONSTRAINT bobo_tools_portal_options_fk1 FOREIGN KEY (portal_id) REFERENCES bobo.portals(portal_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.validation_options ADD CONSTRAINT bobo_tools_validation_options_fk1 FOREIGN KEY (option_user) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.validation_trees ADD CONSTRAINT bobo_tools_validation_trees_fk1 FOREIGN KEY (tree_owner) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.validation_trees_groups ADD CONSTRAINT bobo_tools_validation_trees_groups_fk1 FOREIGN KEY (tree_id) REFERENCES bobo_tools.validation_trees(tree_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.validation_trees_groups ADD CONSTRAINT bobo_tools_validation_trees_groups_fk2 FOREIGN KEY (gr_id) REFERENCES bobo.groups(gr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.validation_trees_pages ADD CONSTRAINT bobo_tools_validation_trees_pages_fk1 FOREIGN KEY (tree_id) REFERENCES bobo_tools.validation_trees(tree_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.validation_trees_pages ADD CONSTRAINT bobo_tools_validation_trees_pages_fk2 FOREIGN KEY (page_id) REFERENCES bobo_tools.visualizer_pages(page_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.visualizer_categories ADD CONSTRAINT bobo_tools_visualizer_categories_fk1 FOREIGN KEY (cat_owner) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.visualizer_category_groups ADD CONSTRAINT bobo_tools_visualizer_category_groups_fk1 FOREIGN KEY (cat_id) REFERENCES bobo_tools.visualizer_categories(cat_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.visualizer_category_groups ADD CONSTRAINT bobo_tools_visualizer_category_groups_fk2 FOREIGN KEY (gr_id) REFERENCES bobo.groups(gr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.visualizer_macros ADD CONSTRAINT bobo_tools_visualizer_macros_fk1 FOREIGN KEY (macro_page) REFERENCES bobo_tools.visualizer_pages(page_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.visualizer_options ADD CONSTRAINT bobo_tools_visualizer_options_fk1 FOREIGN KEY (option_user) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY bobo_tools.visualizer_pages ADD CONSTRAINT bobo_tools_visualizer_pages_fk1 FOREIGN KEY (page_category) REFERENCES bobo_tools.visualizer_categories(cat_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.calibrations_result ADD CONSTRAINT calibrations_result_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY clients.alarms ADD CONSTRAINT clients_alarms_fk2 FOREIGN KEY (param_id) REFERENCES metadata.parameters(param_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.auto_validation_results ADD CONSTRAINT clients_auto_validation_results_fkey FOREIGN KEY (stpr_id) REFERENCES metadata.stations_parameters(stpr_id) ON DELETE RESTRICT;
ALTER TABLE ONLY clients.calibrations_data ADD CONSTRAINT clients_calibrations_data_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY clients.data_coverage ADD CONSTRAINT clients_data_coverage_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY clients.derenda_warnings ADD CONSTRAINT clients_derenda_warnings_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.envea_warnings ADD CONSTRAINT clients_envea_warnings_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.fidas_warnings ADD CONSTRAINT clients_fidas_warnings_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.final_validation_log ADD CONSTRAINT clients_final_validation_log_fk1 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.final_validation_log ADD CONSTRAINT clients_final_validation_log_fk2 FOREIGN KEY (stpr_id) REFERENCES metadata.stations_parameters(stpr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.final_validation_log ADD CONSTRAINT clients_final_validation_log_fk3 FOREIGN KEY (fvc_code_id) REFERENCES metadata.final_validation_codes(fvc_code_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.instruments_last_update ADD CONSTRAINT clients_instruments_last_update_fk FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.jobs_queue ADD CONSTRAINT clients_jobs_queue_fkey FOREIGN KEY (job_id) REFERENCES clients.jobs(job_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.jobs_queue ADD CONSTRAINT clients_jobs_queue_fkey2 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.metone_warnings ADD CONSTRAINT clients_metone_warnings_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.param_limits ADD CONSTRAINT clients_param_limits_fkey FOREIGN KEY (param_id) REFERENCES metadata.parameters(param_id) ON DELETE RESTRICT;
ALTER TABLE ONLY clients.stations_alarms ADD CONSTRAINT clients_stations_alarms_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.stations_alarms ADD CONSTRAINT clients_stations_alarms_fkey2 FOREIGN KEY (param_id) REFERENCES metadata.parameters(param_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.stations_alarms ADD CONSTRAINT clients_stations_alarms_fkey3 FOREIGN KEY (stpr_id) REFERENCES metadata.stations_parameters(stpr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.stations_last_update ADD CONSTRAINT clients_stations_last_update_fk FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.stations_param_limits ADD CONSTRAINT clients_stations_param_limits_fkey FOREIGN KEY (stpr_id) REFERENCES metadata.stations_parameters(stpr_id) ON DELETE RESTRICT;
ALTER TABLE ONLY clients.swam_warnings ADD CONSTRAINT clients_swam_warnings_fk1 FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.tecora_data ADD CONSTRAINT clients_tecora_data_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.tecora_warnings ADD CONSTRAINT clients_tecora_warnings_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.teledyne_warnings ADD CONSTRAINT clients_teledyne_warnings_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.trigger_history ADD CONSTRAINT clients_trigger_history_fk1 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients.trigger_history ADD CONSTRAINT clients_trigger_history_fk2 FOREIGN KEY (ann_id) REFERENCES bobo_tools.annotations(ann_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.runs ADD CONSTRAINT clients_stats_runs_fkey FOREIGN KEY (province_id) REFERENCES main.provinces (province_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY clients_stats.runs ADD CONSTRAINT clients_stats_runs_fkey2 FOREIGN KEY (run_pdf_creator) REFERENCES bobo.users (us_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY clients_stats.runs ADD CONSTRAINT clients_stats_runs_fkey3 FOREIGN KEY (us_id) REFERENCES bobo.users (us_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY clients_stats.limits ADD CONSTRAINT clients_stats_limits_fkey2 FOREIGN KEY (stat_id) REFERENCES clients_stats.statistics(stat_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.limits ADD CONSTRAINT clients_stats_limits_fkey3 FOREIGN KEY (lt_id) REFERENCES clients_stats.limits_type(lt_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.report_results ADD CONSTRAINT clients_stats_report_results_fk1 FOREIGN KEY (stpr_id) REFERENCES metadata.stations_parameters(stpr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.report_results ADD CONSTRAINT clients_stats_report_results_fk2 FOREIGN KEY (rt_id) REFERENCES clients_stats.report_types(rt_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.report_results ADD CONSTRAINT clients_stats_report_results_fk3 FOREIGN KEY (rs_id) REFERENCES clients_stats.report_stats(rs_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.report_type_stats ADD CONSTRAINT clients_stats_report_type_stats_fk1 FOREIGN KEY (portal_id) REFERENCES bobo.portals(portal_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.report_type_stats ADD CONSTRAINT clients_stats_report_type_stats_fk2 FOREIGN KEY (rt_id) REFERENCES clients_stats.report_types(rt_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.report_type_stats ADD CONSTRAINT clients_stats_report_type_stats_fk3 FOREIGN KEY (rs_id) REFERENCES clients_stats.report_stats(rs_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.reports ADD CONSTRAINT clients_stats_reports_fk1 FOREIGN KEY (rt_id) REFERENCES clients_stats.report_types(rt_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.reports ADD CONSTRAINT clients_stats_reports_fk2 FOREIGN KEY (sz_id) REFERENCES clients_stats.stations_zones(sz_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.reports ADD CONSTRAINT clients_stats_reports_fk3 FOREIGN KEY (param_id) REFERENCES metadata.parameters(param_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.reports ADD CONSTRAINT clients_stats_reports_fk4 FOREIGN KEY (rep_signer) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.reports ADD CONSTRAINT clients_stats_reports_fk5 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.results ADD CONSTRAINT clients_stats_results_fkey1 FOREIGN KEY (stpr_id) REFERENCES metadata.stations_parameters(stpr_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY clients_stats.results ADD CONSTRAINT clients_stats_results_fkey2 FOREIGN KEY (limit_id) REFERENCES clients_stats.limits(limit_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY clients_stats.stations_zones ADD CONSTRAINT clients_stats_stations_zones_fk1 FOREIGN KEY (portal_id) REFERENCES bobo.portals(portal_id) ON UPDATE CASCADE;
ALTER TABLE ONLY clients_stats.stations_zones ADD CONSTRAINT clients_stats_stations_zones_fk2 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.cylinder_attachments ADD CONSTRAINT equipments_cylinder_attachments_fk1 FOREIGN KEY (cy_id) REFERENCES equipments.cylinders(cy_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.cylinders ADD CONSTRAINT equipments_cylinders_fkey1 FOREIGN KEY (category_id) REFERENCES equipments.categories(category_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.cylinders ADD CONSTRAINT equipments_cylinders_fkey2 FOREIGN KEY (insert_user) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.instrument_attachments ADD CONSTRAINT equipments_instrument_attachments_fk1 FOREIGN KEY (instr_id) REFERENCES equipments.instruments(instr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.instruments ADD CONSTRAINT equipments_instruments_fkey1 FOREIGN KEY (instr_type_id) REFERENCES equipments.instruments_type(instr_type_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.instruments ADD CONSTRAINT equipments_instruments_fkey2 FOREIGN KEY (insert_user) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.instruments_operations ADD CONSTRAINT equipments_instruments_operations_fk1 FOREIGN KEY (category_id) REFERENCES equipments.categories(category_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.instruments_operations ADD CONSTRAINT equipments_instruments_operations_fk2 FOREIGN KEY (instr_type_id) REFERENCES equipments.instruments_type(instr_type_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.instruments_operations ADD CONSTRAINT equipments_instruments_operations_fk3 FOREIGN KEY (op_id) REFERENCES equipments.operations(op_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.instruments_operations ADD CONSTRAINT equipments_instruments_operations_fk4 FOREIGN KEY (op_ca_id) REFERENCES equipments.operations_category(op_ca_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.instruments_operations ADD CONSTRAINT equipments_instruments_operations_fk5 FOREIGN KEY (freq_id) REFERENCES equipments.frequencies(freq_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.instruments_type ADD CONSTRAINT equipments_instruments_type_fkey1 FOREIGN KEY (constr_id) REFERENCES equipments.constructors(constr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.instruments_type ADD CONSTRAINT equipments_instruments_type_fkey2 FOREIGN KEY (brand_id) REFERENCES equipments.brands(brand_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.instruments_type ADD CONSTRAINT equipments_instruments_type_fkey3 FOREIGN KEY (model_id) REFERENCES equipments.models(model_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.instruments_type ADD CONSTRAINT equipments_instruments_type_fkey4 FOREIGN KEY (category_id) REFERENCES equipments.categories(category_id) ON UPDATE CASCADE;
ALTER TABLE ONLY equipments.miscellany_attachments ADD CONSTRAINT equipments_miscellany_attachments_fk1 FOREIGN KEY (mi_id) REFERENCES equipments.miscellanies(mi_id) ON UPDATE CASCADE;
ALTER TABLE ONLY gateways.external_emails ADD CONSTRAINT gateways_external_emails_fkey FOREIGN KEY (comp_id) REFERENCES bobo.companies(comp_id) ON UPDATE CASCADE;
ALTER TABLE ONLY gateways.mailing_list ADD CONSTRAINT gateways_mailing_list_fkey1 FOREIGN KEY (comp_id) REFERENCES bobo.companies(comp_id) ON UPDATE CASCADE;
ALTER TABLE ONLY gateways.mailing_list ADD CONSTRAINT gateways_mailing_list_fkey2 FOREIGN KEY (portal_id) REFERENCES bobo.portals(portal_id) ON UPDATE CASCADE;
ALTER TABLE ONLY gateways.mlist_external_mails ADD CONSTRAINT gateways_mlist_external_mails_fkey1 FOREIGN KEY (ml_id) REFERENCES gateways.mailing_list(ml_id) ON UPDATE CASCADE;
ALTER TABLE ONLY gateways.mlist_external_mails ADD CONSTRAINT gateways_mlist_external_mails_fkey2 FOREIGN KEY (ee_id) REFERENCES gateways.external_emails(ee_id) ON UPDATE CASCADE;
ALTER TABLE ONLY gateways.mlist_users ADD CONSTRAINT gateways_mlist_users_fkey1 FOREIGN KEY (ml_id) REFERENCES gateways.mailing_list(ml_id) ON UPDATE CASCADE;
ALTER TABLE ONLY gateways.mlist_users ADD CONSTRAINT gateways_mlist_users_fkey2 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY gateways.telegrams ADD CONSTRAINT gateways_telegrams_fkey FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY main.province_municipalities ADD CONSTRAINT main_province_municipalities_fk1 FOREIGN KEY (province_id) REFERENCES main.provinces(province_id) ON UPDATE CASCADE;
ALTER TABLE ONLY main.province_municipalities ADD CONSTRAINT main_province_municipalities_fk2 FOREIGN KEY (mu_id) REFERENCES main.municipalities(mu_id) ON UPDATE CASCADE;
ALTER TABLE ONLY main.region_provinces ADD CONSTRAINT main_region_provinces_fk1 FOREIGN KEY (region_id) REFERENCES main.regions(region_id) ON UPDATE CASCADE;
ALTER TABLE ONLY main.region_provinces ADD CONSTRAINT main_region_provinces_fk2 FOREIGN KEY (province_id) REFERENCES main.provinces(province_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.app_aggregations ADD CONSTRAINT metadata_app_aggregations_fk1 FOREIGN KEY (measure_cadence_id) REFERENCES metadata.measures_cadence(measure_cadence_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.diagnostics ADD CONSTRAINT metadata_diagnostics_fkey1 FOREIGN KEY (param_id_fk) REFERENCES metadata.parameters(param_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.diagnostics ADD CONSTRAINT metadata_diagnostics_fkey2 FOREIGN KEY (instr_type_id_fk) REFERENCES equipments.instruments_type(instr_type_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.parameters_conversions ADD CONSTRAINT metadata_parameters_conversions_fkey FOREIGN KEY (param_id) REFERENCES metadata.parameters(param_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.parameters_info ADD CONSTRAINT metadata_parameters_info_fk1 FOREIGN KEY (pm_info_type_fk) REFERENCES metadata.parameters_type(pm_type_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.parameters_info ADD CONSTRAINT metadata_parameters_info_fk2 FOREIGN KEY (param_id) REFERENCES metadata.parameters(param_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.site_attachments ADD CONSTRAINT metadata_site_attachments_fk1 FOREIGN KEY (site_id) REFERENCES metadata.sites(site_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.sites ADD CONSTRAINT metadata_sites_fk1 FOREIGN KEY (mu_id) REFERENCES main.municipalities(mu_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_cylinders ADD CONSTRAINT metadata_stations_cylinders_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_cylinders ADD CONSTRAINT metadata_stations_cylinders_fkey2 FOREIGN KEY (cy_id) REFERENCES equipments.cylinders(cy_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_info ADD CONSTRAINT metadata_stations_info_fk1 FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_info ADD CONSTRAINT metadata_stations_info_fk2 FOREIGN KEY (st_info_network_type_fk) REFERENCES metadata.stations_network_type(st_network_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_info ADD CONSTRAINT metadata_stations_info_fk3 FOREIGN KEY (st_info_roaming_type_fk) REFERENCES metadata.stations_roaming_type(st_roaming_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_info ADD CONSTRAINT metadata_stations_info_fk4 FOREIGN KEY (st_info_typology_fk) REFERENCES metadata.stations_typology(st_typology_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_info ADD CONSTRAINT metadata_stations_info_fk6 FOREIGN KEY (st_info_cadence_fk) REFERENCES metadata.measures_cadence(measure_cadence_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_info ADD CONSTRAINT metadata_stations_info_fkey5 FOREIGN KEY (st_info_measure_fk) REFERENCES metadata.measures_type(measure_type_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_instruments ADD CONSTRAINT metadata_stations_instruments_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_instruments ADD CONSTRAINT metadata_stations_instruments_fkey2 FOREIGN KEY (instr_id) REFERENCES equipments.instruments(instr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_miscellanies ADD CONSTRAINT metadata_stations_miscellanies_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_miscellanies ADD CONSTRAINT metadata_stations_miscellanies_fkey2 FOREIGN KEY (mi_id) REFERENCES equipments.miscellanies(mi_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_municipality ADD CONSTRAINT metadata_stations_municipality_fkey1 FOREIGN KEY (mu_id) REFERENCES main.municipalities(mu_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_municipality ADD CONSTRAINT metadata_stations_municipality_fkey2 FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_parameters ADD CONSTRAINT metadata_stations_parameters_fkey1 FOREIGN KEY (param_id) REFERENCES metadata.parameters(param_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_parameters ADD CONSTRAINT metadata_stations_parameters_fkey2 FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_params_info ADD CONSTRAINT metadata_stations_params_info_fkey1 FOREIGN KEY (stpr_id) REFERENCES metadata.stations_parameters(stpr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_params_info ADD CONSTRAINT metadata_stations_params_info_fkey2 FOREIGN KEY (stpr_info_measure_fk) REFERENCES metadata.measures_type(measure_type_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_params_info ADD CONSTRAINT metadata_stations_params_info_fkey3 FOREIGN KEY (stpr_info_cadence_fk) REFERENCES metadata.measures_cadence(measure_cadence_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_params_status ADD CONSTRAINT metadata_stations_params_status_fkey1 FOREIGN KEY (stpr_id) REFERENCES metadata.stations_parameters(stpr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_sites ADD CONSTRAINT metadata_stations_sites_fkey FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_sites ADD CONSTRAINT metadata_stations_sites_fkey2 FOREIGN KEY (station_override_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_sites ADD CONSTRAINT metadata_stations_sites_fkey3 FOREIGN KEY (site_id) REFERENCES metadata.sites(site_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_sites ADD CONSTRAINT metadata_stations_sites_fkey4 FOREIGN KEY (camp_id) REFERENCES metadata.campaigns(camp_id) ON UPDATE CASCADE;
ALTER TABLE ONLY metadata.stations_status ADD CONSTRAINT metadata_stations_status_fk1 FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.calibration_attachments ADD CONSTRAINT reports_calibration_attachments_fk1 FOREIGN KEY (calib_id) REFERENCES reports.calibrations(calib_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.calibrations ADD CONSTRAINT reports_calibrations_fk1 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.calibrations ADD CONSTRAINT reports_calibrations_fk2 FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.calibrations ADD CONSTRAINT reports_calibrations_fk3 FOREIGN KEY (instr_id) REFERENCES equipments.instruments(instr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.calibrations ADD CONSTRAINT reports_calibrations_fk4 FOREIGN KEY (calib_re_id) REFERENCES reports.calibration_reasons(calib_re_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.inspection_attachments ADD CONSTRAINT reports_inspection_attachments_fk1 FOREIGN KEY (insp_id) REFERENCES reports.inspections(insp_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.inspections ADD CONSTRAINT reports_inspections_fk1 FOREIGN KEY (mu_id) REFERENCES main.municipalities(mu_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.inspections ADD CONSTRAINT reports_inspections_fk2 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.maintenances_operations ADD CONSTRAINT reports_maintenance_operations_fk1 FOREIGN KEY (ma_id) REFERENCES reports.maintenances(ma_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.maintenances_operations ADD CONSTRAINT reports_maintenance_operations_fk2 FOREIGN KEY (instr_id) REFERENCES equipments.instruments(instr_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.maintenances_operations ADD CONSTRAINT reports_maintenance_operations_fk3 FOREIGN KEY (in_op_id) REFERENCES equipments.instruments_operations(in_op_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.maintenances_operations ADD CONSTRAINT reports_maintenance_operations_fk4 FOREIGN KEY (calib_id) REFERENCES reports.calibrations(calib_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.maintenances ADD CONSTRAINT reports_maintenances_fk1 FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.maintenances ADD CONSTRAINT reports_maintenances_fk2 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.maintenances_miscellanies_operations ADD CONSTRAINT reports_maintenances_miscellanies_operations_fk1 FOREIGN KEY (ma_id) REFERENCES reports.maintenances(ma_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.maintenances_miscellanies_operations ADD CONSTRAINT reports_maintenances_miscellanies_operations_fk2 FOREIGN KEY (mi_id) REFERENCES equipments.miscellanies(mi_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.maintenances_miscellanies_operations ADD CONSTRAINT reports_maintenances_miscellanies_operations_fk3 FOREIGN KEY (mi_op_id) REFERENCES equipments.miscellanies_operations(mi_op_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.meetings ADD CONSTRAINT reports_meetings_fk1 FOREIGN KEY (province_id) REFERENCES main.provinces(province_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.meetings ADD CONSTRAINT reports_meetings_fk2 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.message_destinations ADD CONSTRAINT reports_message_destinations_fk1 FOREIGN KEY (msg_id) REFERENCES reports.messages(msg_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.message_destinations ADD CONSTRAINT reports_message_destinations_fk2 FOREIGN KEY (dest_id) REFERENCES reports.destinations(dest_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.messages ADD CONSTRAINT reports_messages_fk1 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE;
ALTER TABLE ONLY reports.tickets ADD CONSTRAINT reports_tickets_fkey FOREIGN KEY (tk_parent_id_fk) REFERENCES reports.tickets(tk_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets ADD CONSTRAINT reports_tickets_fkey10 FOREIGN KEY (tu_id) REFERENCES reports.ticket_urgencies(tu_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets ADD CONSTRAINT reports_tickets_fkey11 FOREIGN KEY (tf_id) REFERENCES reports.ticket_frequencies(tf_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets ADD CONSTRAINT reports_tickets_fkey2 FOREIGN KEY (tk_opening_user_fk) REFERENCES bobo.users(us_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets ADD CONSTRAINT reports_tickets_fkey3 FOREIGN KEY (tk_recipient_comp_fk) REFERENCES bobo.companies(comp_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets ADD CONSTRAINT reports_tickets_fkey4 FOREIGN KEY (station_id) REFERENCES metadata.stations(station_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets ADD CONSTRAINT reports_tickets_fkey5 FOREIGN KEY (instr_id) REFERENCES equipments.instruments(instr_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets ADD CONSTRAINT reports_tickets_fkey6 FOREIGN KEY (cy_id) REFERENCES equipments.cylinders(cy_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets ADD CONSTRAINT reports_tickets_fkey7 FOREIGN KEY (mi_id) REFERENCES equipments.miscellanies(mi_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets ADD CONSTRAINT reports_tickets_fkey8 FOREIGN KEY (tt_id) REFERENCES reports.ticket_types(tt_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets ADD CONSTRAINT reports_tickets_fkey9 FOREIGN KEY (tc_id) REFERENCES reports.ticket_categories(tc_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets_mlists ADD CONSTRAINT reports_tickets_mlists_fkey FOREIGN KEY (tk_id) REFERENCES reports.tickets(tk_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY reports.tickets_mlists ADD CONSTRAINT reports_tickets_mlists_fkey2 FOREIGN KEY (ml_id) REFERENCES gateways.mailing_list(ml_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY reports.tickets_status ADD CONSTRAINT reports_tickets_status_fkey FOREIGN KEY (tk_id) REFERENCES reports.tickets(tk_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets_status ADD CONSTRAINT reports_tickets_status_fkey2 FOREIGN KEY (us_id) REFERENCES bobo.users(us_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.tickets_status ADD CONSTRAINT reports_tickets_status_fkey3 FOREIGN KEY (ma_id) REFERENCES reports.maintenances(ma_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.ced_tickets ADD CONSTRAINT reports_ced_tickets_fkey2 FOREIGN KEY (us_id) REFERENCES bobo.users (us_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.ced_tickets_status ADD CONSTRAINT reports_ced_tickets_status_fkey FOREIGN KEY (ct_id) REFERENCES reports.ced_tickets (ct_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.ced_tickets_status ADD CONSTRAINT reports_ced_tickets_status_fkey2 FOREIGN KEY (us_id) REFERENCES bobo.users (us_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.ced_tickets_status ADD CONSTRAINT reports_ced_tickets_status_fkey3 FOREIGN KEY (gr_id) REFERENCES bobo.groups (gr_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.ced_tickets_status ADD CONSTRAINT reports_ced_tickets_status_fkey4 FOREIGN KEY (ctt_id) REFERENCES reports.ced_ticket_types (ctt_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.ced_tickets_status ADD CONSTRAINT reports_ced_tickets_status_fkey5 FOREIGN KEY (ctu_id) REFERENCES reports.ced_ticket_urgencies (ctu_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY reports.ced_tickets_status_attachments ADD CONSTRAINT reports_ced_tickets_status_attachments_fk1 FOREIGN KEY (cts_id) REFERENCES reports.ced_tickets_status (cts_id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE ONLY client_lig_alims.filters ADD CONSTRAINT client_lig_alims_filters_fkey1 FOREIGN KEY (rep_id) REFERENCES client_lig_alims.reports (rep_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY client_lig_alims.reports ADD CONSTRAINT client_lig_alims_reports_fkey1 FOREIGN KEY (us_id) REFERENCES bobo.users (us_id) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE ONLY client_lig_alims.reports ADD CONSTRAINT client_lig_alims_reports_fkey2 FOREIGN KEY (arg_id) REFERENCES client_lig_alims.arguments (arg_id) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE ONLY client_lig_alims.reports ADD CONSTRAINT client_lig_alims_reports_fkey3 FOREIGN KEY (station_id) REFERENCES metadata.stations (station_id) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE ONLY client_lig_alims.reports ADD CONSTRAINT client_lig_alims_reports_fkey4 FOREIGN KEY (instr_id) REFERENCES equipments.instruments (instr_id) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE ONLY infoaria.params_pollutant ADD CONSTRAINT infoaria_params_pollutant_fk1 FOREIGN KEY (param_id) REFERENCES metadata.parameters (param_id) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE ONLY infoaria.params_pollutant ADD CONSTRAINT infoaria_params_pollutant_fk2 FOREIGN KEY (pollutant_id) REFERENCES infoaria.pollutants (pollutant_id) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE ONLY infoaria.params_pollutant ADD CONSTRAINT infoaria_params_pollutant_fk3 FOREIGN KEY (observation_unit_id) REFERENCES infoaria.observation_units (observation_unit_id) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE ONLY infoaria.stations_params_e2a ADD CONSTRAINT infoaria_stations_params_e2a_fk1 FOREIGN KEY (stpr_id) REFERENCES metadata.stations_parameters (stpr_id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE ONLY infoaria.stations_params_status ADD CONSTRAINT infoaria_stations_params_status_fk1 FOREIGN KEY (stpr_id) REFERENCES metadata.stations_parameters (stpr_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;