#--------------------------------------------------------
# application config file
#--------------------------------------------------------
{
    # infos
    version => "2.0",
    title   => "OPAS",
    url     => "https://opastest.it",
    perldoc => 0,
    secrets => [''],

    # server config
    hypnotoad => {
        listen  => ['http://*:8080'],

        # Number of worker processes, defaults to the value of "workers" in Mojo::Server::Prefork.
        # A good rule of thumb is two worker processes per CPU
        workers => 8,

        # Maximum number of accepted connections each worker process is allowed to handle concurrently
        clients => 100,

        # Maximum amount of time in seconds before a worker without a heartbeat will be stopped gracefully
        heartbeat_timeout => 360
    },

    # mail logo
    logo_mail   => 'opas',

	# portal name
    portal_name => 'OPAS',

    # maintenance
    maintenance => 0
}
