#--------------------------------------------------------
# configuration PRODUCTION
#--------------------------------------------------------
{
    # mode_type => "PRODUCTION",

    # log
    logpath => '',
    loglevel => 'debug', # debug | info | warning

    # LOGIN page
    login_page => 'login',

    # version DB
    version_db => 2.0,

    # enable public routes (dataview)
    public_routes => 1, # 0 false, 1 true in order to enable public routes

    # database connection
    database => 'postgresql://user:pass@host:port/dbname?pg_enable_utf8=1&application_name="app.name"',
}
